# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)


config.set('content.cookies.accept', 'all', 'chrome-devtools://*')
config.set('content.cookies.accept', 'all', 'devtools://*')
config.set('content.cookies.accept', 'all', 'qute://*/*')
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:144.0) Gecko/20100101 Firefox/144.0', 'https://accounts.google.com/*')
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}', 'https://gitlab.gnome.org/*')
config.set('content.images', True, 'chrome-devtools://*')
config.set('content.images', True, 'devtools://*')
config.set('content.images', True, 'qute://*/*')
config.set('content.javascript.enabled', True, 'chrome-devtools://*')
config.set('content.javascript.enabled', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'chrome://*/*')
config.set('content.javascript.enabled', True, 'qute://*/*')
config.set('content.javascript.enabled', True)

config.set('content.cookies.accept', 'no-3rdparty')
config.set('content.cookies.store', True)
config.set('content.blocking.enabled', True)
config.source('cookies_whitelist.py')

c.tabs.position = "left"
c.tabs.width = '10%'
c.completion.shrink = True

c.input.insert_mode.auto_leave = True
c.input.insert_mode.auto_enter = True

import dracula.draw

dracula.draw.blood(c, {
    'spacing': {
        'vertical': 6,
        'horizontal': 2
    }
})

c.colors.webpage.darkmode.enabled = False
# c.colors.webpage.darkmode.algorithm = 'brightness-rgb'
c.colors.webpage.preferred_color_scheme = 'dark'
c.fonts.default_size = '10pt'
c.scrolling.smooth = False
c.content.prefers_reduced_motion = True


c.content.headers.do_not_track = True
c.content.canvas_reading = False
config.set('content.canvas_reading', True, 'qute://*/*')
c.content.geolocation = False
c.content.media.audio_capture = False
c.content.media.video_capture = False
c.content.webgl = False
c.content.webrtc_ip_handling_policy = 'disable-non-proxied-udp'
c.content.autoplay = False
c.content.pdfjs = True
c.auto_save.session = True

c.downloads.location.directory = '~/Downloads/browser'
c.editor.command = ['kitty', 'nvim', '{file}']
c.fileselect.handler = 'default'

config.set('content.headers.user_agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36')

c.content.proxy = "socks5://127.0.0.1:2080"
config.bind('xo', 'set content.proxy socks5://127.0.0.1:2080')
config.bind('xO', 'set content.proxy system')

config.bind(';m', 'hint links spawn mpv {hint-url}')

config.bind(';q', 'jseval -q document.activeElement.blur()')
config.bind('tT', 'config-cycle tabs.position top left')

c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'aw': 'https://wiki.archlinux.org/index.php?search={}',
    'ru': 'https://rutracker.org/forum/tracker.php?nm={}',
    'yt': 'https://www.youtube.com/results?search_query={}',
}

c.content.javascript.log_message.excludes = {"userscript:_qute_stylesheet": ["*Refused to apply inline style because it violates the following Content Security Policy directive: *"], "userscript:_qute_js": ["*TrustedHTML*"]}

c.bindings.key_mappings = { 
        'й' : 'q',
        'ц' : 'w',
        'у' : 'e',
        'к' : 'r',
        'е' : 't',
        'н' : 'y',
        'г' : 'u',
        'ш' : 'i',
        'щ' : 'o',
        'з' : 'p',
        'х' : '[',
        'ъ' : ']',
        'ф' : 'a',
        'ы' : 's',
        'в' : 'd',
        'а' : 'f',
        'п' : 'g',
        'р' : 'h',
        'о' : 'j',
        'л' : 'k',
        'д' : 'l',
        'ж' : ';',
        'э' : '\'',
        'я' : 'z',
        'ч' : 'x',
        'с' : 'c',
        'м' : 'v',
        'и' : 'b',
        'т' : 'n',
        'ь' : 'm',
        'б' : ',',
        'ю' : '.',
        'ё' : '`',
        'Й' : 'Q',
        'Ц' : 'W',
        'У' : 'E',
        'К' : 'R',
        'Е' : 'T',
        'Н' : 'Y',
        'Г' : 'U',
        'Ш' : 'I',
        'Щ' : 'O',
        'Х' : '{',
        'Ъ' : '}',
        'Ф' : 'A',
        'Ы' : 'S',
        'В' : 'D',
        'А' : 'F',
        'П' : 'G',
        'Р' : 'H',
        'О' : 'J',
        'Л' : 'K',
        'Д' : 'L',
        'Ж' : ':',
        'Э' : '\"',
        'Я' : 'Z',
        'Ч' : 'X',
        'С' : 'C',
        'М' : 'V',
        'И' : 'B',
        'Т' : 'N',
        'Ь' : 'M',
        'Б' : '<',
        'Ю' : '>',
        'Ё' : '~',
        '<Ctrl-С>' : '<Ctrl-C>',
        '<Ctrl-М>' : '<Ctrl-V>'
}

c.content.blocking.enabled = True
c.content.blocking.method = 'both'
c.content.blocking.adblock.lists = [
    'https://easylist.to/easylist/easylist.txt',
    'https://easylist.to/easylist/easyprivacy.txt',
    'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt',
    'https://github.com/uBlockOrigin/uAssets/raw/master/filters/resource-abuse.txt',
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/legacy.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2020.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2021.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2022.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2023.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2024.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badware.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/privacy.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badlists.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances-cookies.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances-others.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badlists.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/quick-fixes.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/resource-abuse.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/unbreak.txt"
]

